apiVersion: v1
kind: Service
metadata:
        name: ingress-service
spec:
        selector:
                app: ingresstest
        ports:
                - protocol: TCP
                  port: 80
                  targetPort: 3000
        type: NodePort
